# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "C:/Users/salam/AppData/Local/Temp/RtmpSmvwCg/pins-2f382fa576d6")
v <- vetiver_pin_read(b, "lego-sets")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
