---
title: "baseball_racing"
output: html_document
editor_options: 
  chunk_output_type: console
---
## https://www.kaggle.com/c/sliced-s01e09-playoffs-1/
```{r}
library(tidyverse)

train_raw <- read_csv("data/baseball_train.csv")
```

```{r}
train_raw %>% 
  ggplot(aes(plate_x, plate_z, z = is_home_run)) +
  stat_summary_hex(alpha = 0.8, bins = 10) +
  scale_fill_viridis_c(labels = scales::percent) +
  labs(
    fill = "% home runs"
  )
```

```{r}
train_raw %>%
  ggplot(aes(launch_angle, launch_speed, z = is_home_run)) +
  stat_summary_hex(alpha = 0.8, bins = 15) +
  scale_fill_viridis_c(labels = scales::percent) +
  labs(
    fill = "% home runs"
    )
```

```{r}
train_raw %>% 
  mutate(is_home_run = if_else(as.logical(is_home_run), "yes", "no")) %>% 
  select(is_home_run, balls, strikes, inning) %>% 
  pivot_longer(balls:inning) %>% 
  mutate(name = fct_inorder(name)) %>% 
  ggplot(aes(value, after_stat(density), fill = is_home_run)) +
  geom_histogram(alpha = 0.5, binwidth = 1, position = "identity") +
  facet_wrap(~name, scales = "free") +
  labs(
    fill = "Home run?"
  )
```
### Build a model
```{r}
library(tidymodels)

set.seed(123)
bb_split <- train_raw %>% 
  mutate(
    is_home_run = if_else(as.logical(is_home_run), "HR", "no"),
    is_home_run = factor(is_home_run)
  ) %>% 
  initial_split(strata = is_home_run)

bb_train <- training(bb_split)
bb_test <- testing(bb_split)

set.seed(234)
bb_folds <- vfold_cv(bb_train, strata = is_home_run)
```

```{r}
# bb_train %>% glimpse()
# bb_train %>% count(bb_type)
# bb_train %>% count(bearing)

bb_rec <- recipe(
  is_home_run ~ launch_angle + launch_speed + plate_x + plate_z + bb_type + 
    bearing + pitch_mph + is_pitcher_lefty + is_batter_lefty + inning + balls + 
    strikes + game_date,
  data = bb_train
) %>% 
  step_date(game_date, features = c("week"), keep_original_cols = FALSE) %>% 
  step_unknown(all_nominal_predictors()) %>% 
  step_dummy(all_nominal_predictors(), one_hot = TRUE) %>% 
  step_impute_median(all_numeric_predictors(), -launch_angle, -launch_speed) %>% 
  step_impute_linear(launch_angle, launch_speed,
                     impute_with = imp_vars(plate_x, plate_z, pitch_mph)) %>% 
  step_nzv(all_predictors())

prep(bb_rec)
```

```{r}
xgb_spec <- boost_tree(
  trees = tune(),
  min_n = tune(),
  mtry = tune(),
  learn_rate = 0.01
) %>% 
  set_engine("xgboost") %>% 
  set_mode("classification")

xgb_wf <- workflow(bb_rec, xgb_spec)
```
## ANOVA racing strategy
```{r}
library(finetune)
#doParallel::registerDoParallel()
library(tune)
library(future)
plan(multisession)

set.seed(345)
xgb_rs <- tune_race_anova(
  xgb_wf,
  resamples = bb_folds,
  grid = 15,
  metrics = metric_set(mn_log_loss),
  control = control_race(verbose_elim = TRUE)
)

plot_race(xgb_rs)
show_best(xgb_rs)
```

```{r}
xgb_last <- xgb_wf %>% 
  finalize_workflow(select_best(xgb_rs, metric = "mn_log_loss")) %>% 
  last_fit(bb_split)

collect_predictions(xgb_last) %>% 
  mn_log_loss(is_home_run, .pred_HR)
```

```{r}
library(vip)

extract_workflow(xgb_last) %>% 
  extract_fit_parsnip() %>% 
  vip(geom = "point", num_features = 15)
```
