---
title: "billboard_100"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

## billboard ranking data
billboard <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/billboard.csv")

## spotify feature data
audio_features <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/audio_features.csv")
```

```{r}
max_weeks <- billboard %>% 
  group_by(song_id) %>% 
  summarise(weeks_on_chart = max(weeks_on_chart), .groups = "drop")
```

```{r}
billboard_joined <- audio_features %>% 
  filter(!is.na(spotify_track_popularity)) %>% 
  inner_join(max_weeks)
```

```{r}
billboard_joined %>% 
  filter(tempo > 0, time_signature > 1) %>% 
  ggplot(aes(tempo, fill = factor(time_signature))) +
  geom_histogram(alpha = 0.5, position = "identity") +
  labs(
    fill = "time signature"
  )
```

```{r}
library(corrr)

billboard_joined %>% 
  select(danceability:weeks_on_chart) %>% 
  na.omit() %>% 
  correlate() %>% 
  rearrange() %>% 
  network_plot(colours = c("orange", "white", "midnightblue"))

summary(billboard_joined$weeks_on_chart)
```
### Dimensionality reduction
```{r}
library(tidymodels)

set.seed(123)
billboard_split <- billboard_joined %>% 
  select(danceability:weeks_on_chart) %>% 
  mutate(weeks_on_chart = log(weeks_on_chart)) %>% 
  na.omit() %>% 
  initial_split(strata = weeks_on_chart)

billboard_train <- training(billboard_split)
billboard_test <- testing(billboard_split)
```

```{r}
billboard_rec <- recipe(weeks_on_chart ~ ., data = billboard_train) %>% 
  step_zv(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors())

rec_trained <- prep(billboard_rec)
# bake(rec_trained, billboard_test)
```

```{r}
library(ggforce)

plot_test_results <- function(recipe, dat = billboard_test) {
  recipe %>%
    prep() %>%
    bake(new_data = dat) %>%
    ggplot() +
    geom_autopoint(aes(color = weeks_on_chart), alpha = 0.4, size = 0.5) +
    geom_autodensity(alpha = .3) +
    facet_matrix(vars(-weeks_on_chart), layer.diag = 2) +
    scale_color_distiller(palette = "BuPu", direction = 1) +
    labs(color = "weeks (log)" )
}
```
## PCA
- linear
- upsupervised
- account for variance
```{r}
rec_trained %>% 
  step_pca(all_numeric_predictors(), num_comp = 4) %>% 
  plot_test_results() +
  ggtitle("Principal Component Analysis")
```

```{r}
# rec_trained %>% 
#   step_pca(all_numeric_predictors(), num_comp = 4) %>% 
#   tidy()

rec_trained %>% 
  step_pca(all_numeric_predictors(), num_comp = 4) %>% 
  prep() %>% 
  tidy(number = 3) %>% 
  filter(component %in% paste0("PC", 1:4)) %>% 
  group_by(component) %>% 
  slice_max(abs(value), n = 5) %>% 
  ungroup() %>% 
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col(alpha = 0.8) +
  facet_wrap(vars(component), scales = "free_y") +
  labs(
    x = "Contribution to principal component",
    y = NULL,
    fill = "Positive ?"
  )
```
## PLS
-very similar to PCA
-supervised
```{r}
rec_trained %>% 
  step_pls(all_numeric_predictors(), outcome = "weeks_on_chart", num_comp = 4) %>% 
  plot_test_results() +
  ggtitle("Partial Least Squares")
```

```{r}
rec_trained %>% 
  step_pls(all_numeric_predictors(), outcome = "weeks_on_chart", num_comp = 4) %>% 
  prep() %>% 
  tidy(number = 3) %>% 
  filter(component %in% paste0("PLS", 1:4)) %>% 
  group_by(component) %>% 
  slice_max(abs(value), n = 5) %>% 
  ungroup() %>% 
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col(alpha = 0.8) +
  facet_wrap(vars(component), scales = "free_y") +
  labs(
    x = "Contribution to PLS component",
    y = NULL,
    fill = "Positive?"
  )
```
## UMAP
-not linear
-very powerful
-based on nearest neighbors + graph networks
```{r}
library(embed)

rec_trained %>% 
  step_umap(all_numeric_predictors(), num_comp = 4) %>% 
  plot_test_results() +
  ggtitle("UMAP")

```













