```{r}
library(tidyverse)
```
## explore data
```{r}
hotels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv")

hotels %>% count(is_canceled)
hotels %>% select(children, babies) %>% sample_n(10)

hotel_stays <- hotels %>% 
  filter(is_canceled == 0) %>% 
  mutate(children = case_when(children + babies > 0 ~ "children",
                              TRUE ~ "none"),
         required_car_parking_spaces = case_when(required_car_parking_spaces > 0 ~ "parking",
                                                 TRUE ~ "none")) %>% 
  select(-is_canceled, -reservation_status, -babies)

hotel_stays %>% count(children)
```

```{r}
library(skimr)
skim(hotel_stays)
```

```{r}
hotel_stays %>% 
  mutate(arrival_date_month = factor(arrival_date_month,
                                     levels = month.name)) %>% 
  count(hotel, arrival_date_month, children) %>% 
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>% 
  ggplot(aes(arrival_date_month, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::label_percent()) +
  facet_wrap(~hotel, nrow = 2)

hotel_stays %>% count(hotel)
```

```{r}
hotel_stays %>% 
  count(hotel, required_car_parking_spaces, children) %>% 
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>% 
  ggplot(aes(required_car_parking_spaces, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::label_percent()) +
  facet_wrap(~hotel, nrow = 2) +
  labs(
    x = NULL,
    y = "Proportion of hotel stays",
    fill = NULL
  )
```

```{r}
library(GGally)

hotel_stays %>% 
  select(children, adr, 
         required_car_parking_spaces, 
         total_of_special_requests) %>% 
  ggpairs(mapping = aes(color = children))
```
## Build models with recipes
```{r}
hotels_df <- hotel_stays %>% 
  select(children, hotel, arrival_date_month, meal, adr, adults,
         required_car_parking_spaces, total_of_special_requests,
         stays_in_week_nights, stays_in_weekend_nights) %>% 
  mutate_if(is.character, factor)
```

```{r}
library(tidymodels)
library(themis)

set.seed(1234)
hotel_split <- initial_split(hotels_df)

hotel_train <- training(hotel_split)
hotel_test <- testing(hotel_split)

hotel_rec <- recipe(children ~ ., data = hotel_train) %>% 
  step_downsample(children) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_numeric()) %>% 
  step_normalize(all_numeric())
  prep()
  
test_proc <- bake(hotel_rec, new_data = hotel_test)
juice(hotel_rec) %>% count(children)
```
## train models
```{r}
knn_spec <- nearest_neighbor() %>% 
  set_engine("kknn") %>% 
  set_mode("classification")

knn_fit <- knn_spec %>% 
  fit(children ~ ., data = juice(hotel_rec))


tree_spec <- decision_tree() %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

tree_fit <- tree_spec %>% 
  fit(children ~ ., data = juice(hotel_rec))
```
## Evaluate models
```{r}
set.seed(1234)
validation_splits <- mc_cv(juice(hotel_rec), prop = 0.9, strata = children)
```

```{r}
knn_res <- fit_resamples(
  knn_spec,
  children ~ .,
  validation_splits,
  control = control_resamples(save_pred = TRUE)
)

knn_res %>% 
  collect_metrics()


tree_res <- fit_resamples(
  tree_spec,
  children ~ .,
  validation_splits,
  control = control_resamples(save_pred = TRUE)
)

tree_res %>% 
  collect_metrics()
```

```{r}
knn_res %>%
  unnest(.predictions) %>% 
  mutate(model = "kknn") %>% 
  bind_rows(tree_res %>% 
              unnest(.predictions) %>% 
              mutate(model = "rpart")) %>% 
  group_by(model) %>% 
  roc_curve(children, .pred_children) %>% 
  autoplot()

knn_res %>% 
  unnest(.predictions) %>% 
  conf_mat(children, .pred_class) %>% 
  autoplot(type = "heatmap")

```

```{r}
knn_fit %>% 
  predict(new_data = test_proc, type = "prob") %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_auc(truth, .pred_children)
```











