---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)

ikea <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-03/ikea.csv")
```

```{r}
ikea %>% 
  ggplot(aes(width, price)) +
  geom_point(alpha = 0.4) +
  scale_y_log10()

ikea %>% 
  rename(X1 = 1) %>% 
  select(X1, price, depth:width) %>% 
  pivot_longer(depth:width, names_to = "dim") %>% 
  ggplot(aes(value, price, color = dim)) +
  geom_point(alpha = 0.4, show.legend = FALSE) +
  scale_y_log10() +
  facet_wrap(~dim, scales = "free_x") +
  labs(
    x = NULL
  )
```

```{r}
ikea %>% count(name, sort = TRUE)

ikea_df <- ikea %>% 
  select(price, name, category, depth, height, width) %>% 
  mutate(price = log10(price)) %>% 
  mutate_if(is.character, factor)
```
### Build a model
```{r}
library(tidymodels)

set.seed(123)
ikea_split <- initial_split(ikea_df, strata = price)
ikea_train <- training(ikea_split)
ikea_test <- testing(ikea_split)

set.seed(234)
ikea_folds <- bootstraps(ikea_train, strata = price)
```

```{r}
library(usemodels)

# get a better practice
use_ranger(price ~ ., data = ikea_train)
```

```{r}
library(textrecipes)
library(parsnip)

ranger_recipe <- 
  recipe(formula = price ~ ., data = ikea_train) %>% 
  step_other(name, category, threshold = 0.01) %>% 
  step_clean_levels(name, category) %>% 
  step_impute_knn(depth, height, width)

ranger_spec <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")

ranger_workflow <- 
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec)

set.seed(8577)
doParallel::registerDoParallel()
ranger_tune <- tune_grid(
  ranger_workflow,
  resamples = ikea_folds,
  grid = 11
)
```
## Explore results
```{r}
show_best(ranger_tune, metric = "rmse")
show_best(ranger_tune, metric = "rsq")
autoplot(ranger_tune)
```

```{r}
final_rf <- ranger_workflow %>% 
  finalize_workflow(select_best(ranger_tune))

ikea_fit <- last_fit(final_rf, ikea_split)
collect_metrics(ikea_fit)
```

```{r}
collect_predictions(ikea_fit) %>% 
  ggplot(aes(price, .pred)) +
  geom_abline(lty = 2, color = "gray50") +
  geom_point(alpha = 0.5, color = "midnightblue") +
  coord_fixed()
```

```{r}
predict(ikea_fit$.workflow[[1]], ikea_test[15, ])
```

```{r}
library(vip)

im_spec <- ranger_spec %>% 
  finalize_model(select_best(ranger_tune)) %>% 
  set_engine("ranger", importance = "permuation")

workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(im_spec) %>% 
  fit(ikea_train) %>% 
  pull_workflow_fit() %>% 
  vip(aesthetics = list(alpha = 0.8, fill = "midnightblue"))

```































