---
title: "map_challenge"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

data("lsl", package = "spDataLarge")
landslides <- as_tibble(lsl)
```

```{r}
ggplot(landslides, aes(x, y)) +
  stat_summary_hex(aes(z = elev), alpha = 0.6, bins = 12) +
  geom_point(aes(color = lslpts), alpha = 0.7) +
  coord_fixed() +
  scale_fill_viridis_c() +
  scale_color_manual(values = c("gray90", "midnightblue")) +
  labs(fill = "Elevation", color = "Landslide ?")
```
## Create spatial resamples
```{r}
library(tidymodels)
library(spatialsample)
library(sf)


# good_folds <- spatial_clustering_cv(landslides, coords = c("x", "y"), v = 5)

range(landslides$x)
range(landslides$y)
 
set.seed(123)
landslides_sf <- st_as_sf(landslides, coords = c("x", "y"), crs = 32717)
good_folds <- spatial_clustering_cv(landslides_sf, v = 5)

set.seed(234)
bad_folds <- vfold_cv(landslides, v = 5, strata = lslpts)
```

```{r}
plot_splits <- function(split) {
  p <- bind_rows(
    analysis(split) %>% 
      mutate(analysis = "Analysis"),
    assessment(split) %>% 
      mutate(analysis = "Assessment")
  ) %>% 
    ggplot(aes(x, y, color = analysis)) +
    geom_point(size = 1.5, alpha = 0.8) +
    coord_fixed() +
    labs(color = NULL)
  print(p)
}
```

```{r}
walk(good_folds$splits, plot_splits)
walk(bad_folds$splits, plot_splits)
```
## Fit and evaluate model
```{r}
glm_spec <- logistic_reg()
lsl_form <- lslpts ~ slope + cplan + cprof + elev + log10_carea

lsl_wf <- workflow(lsl_form, glm_spec)

doParallel::registerDoParallel()
set.seed(2021)
regular_rs <- fit_resamples(lsl_wf, bad_folds)

set.seed(2021)
spatial_rs <- fit_resamples(lsl_wf, good_folds)
```

```{r}
collect_metrics(regular_rs)
collect_metrics(spatial_rs)
```

