---
title: "sf-rents"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

rent_raw <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-05/rent.csv')

rent_raw %>% count(year)
rent_raw %>% slice_sample(n = 20) %>% pull(date)
rent_raw %>% count(room_in_apt)
```

```{r}
rent <- rent_raw %>% 
  filter(room_in_apt < 1, year > 2005) %>% 
  select(date, price, beds, baths) %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  arrange(date)
```
## Computing a sliding mean
```{r}
library(slider)

slide_period_dbl(rent, rent$date, "month", ~mean(.$price))
```

```{r}
mean_rent <- function(df) {
  summarize(df, date = min(date), rent = mean(price), n = n())
}

slide_period_dfr(rent, rent$date, "month", mean_rent)
```

```{r}
slide_period_dfr(rent, rent$date, "month", mean_rent) %>% 
  ggplot(aes(date, rent)) +
  geom_line(size = 1.5, alpha = 0.8)

slide_period_dfr(rent, rent$date, "month", mean_rent, .before = 1) %>% 
  ggplot(aes(date, rent)) +
  geom_line(size = 1.5,  alpha = 0.8)
```
## Different sliding windows
```{r}
tibble(.before = 1:6) %>% 
  mutate(mean_rent = map(
    .before,
    ~slide_period_dfr(rent, rent$date, "month", mean_rent, .before = .x)
  )) %>% 
  unnest(mean_rent) %>% 
  ggplot(aes(date, rent, color = .before, group = .before)) +
  geom_line(alpha = 0.6, size = 1.5) +
  scale_color_viridis_c() +
  scale_y_continuous(labels = scales::dollar) +
  labs(x = NULL, color = "How many months\nin sliding window ?")
```
