---
title: "sliced_ep02"
output: html_document
editor_options: 
  chunk_output_type: console
---
## https://www.kaggle.com/competitions/sliced-s01e02-xunyc5/data?select=train.csv
```{r}
library(tidyverse)

train_raw <- read_csv("data/train.csv", guess_max = 1e5) %>% 
  mutate(damaged = case_when(
    damaged > 0 ~ "damage",
    TRUE ~ "no damage"
  ))

test_raw <- read_csv("data/test.csv", guess_max = 1e5)
```

```{r}
skimr::skim(train_raw)

train_raw %>% count(damaged)
```

```{r}
library(GGally)

train_raw %>% 
  select(damaged, incident_year, height, speed, distance) %>% 
  ggpairs(columns = 2:5, aes(color = damaged, alpha = 0.5))
```

```{r}
train_raw %>% 
  select(
    damaged, precipitation, visibility, engine_type, flight_impact, flight_phase, species_quantity
  ) %>% 
  pivot_longer(precipitation:species_quantity) %>% 
  ggplot(aes(y = value, fill = damaged)) +
  geom_bar(position = "fill") +
  facet_wrap(vars(name), scales = "free", ncol = 2) +
  labs(x = NULL,
       y = NULL,
       fill = NULL)
```

```{r}
bird_df <- train_raw %>% 
  select(
    damaged, flight_impact, precipitation, visibility, flight_phase, engines,
    incident_year, incident_month, species_id, engine_type, aircraft_model,
    species_quantity, height, speed
  )
```
## Build a model
```{r}
library(tidymodels)

set.seed(123)
bird_folds <- vfold_cv(train_raw, v = 5, strata = damaged)

bird_metrics <- metric_set(mn_log_loss, accuracy, sensitivity, specificity)
```

```{r}
bird_rec <- recipe(damaged ~ ., data = bird_df) %>% 
  step_novel(all_nominal_predictors()) %>% 
  step_other(all_nominal_predictors(), threshold = 0.01) %>% 
  step_unknown(all_nominal_predictors()) %>% 
  step_impute_median(all_numeric_predictors()) %>% 
  step_zv(all_predictors())
```

```{r}
library(baguette)

bag_spec <-
  bag_tree(min_n = 10) %>% 
  set_engine("rpart", times = 25) %>% 
  set_mode("classification")

imb_wf <-
  workflow() %>% 
  add_recipe(bird_rec) %>% 
  add_model(bag_spec)

imb_fit <- fit(imb_wf, data = bird_df)
```
## Resample and compare models
```{r}
doParallel::registerDoParallel()

set.seed(123)
imb_rs <- fit_resamples(
  imb_wf,
  resamples = bird_folds,
  metrics = bird_metrics
)

collect_metrics(imb_rs)
```

```{r}
library(themis)

bal_rec <- bird_rec %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_smote(damaged)

bal_wf <-
  workflow() %>% 
  add_recipe(bal_rec) %>% 
  add_model(bag_spec)

set.seed(234)
bal_rs <-
  fit_resamples(
    bal_wf,
    resamples = bird_folds,
    metrics = bird_metrics
  )

collect_metrics(bal_rs)
```

```{r}
test_df <- test_raw %>% 
  select(
    id, flight_impact, precipitation,
    visibility, flight_phase, engines, incident_year,
    incident_month, species_id, engine_type,
    aircraft_model, species_quantity, height, speed
  )

augment(imb_fit, test_df) %>% 
  select(id, .pred_damage)
```























