---
title: "taylor_swift"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(taylor)

glimpse(taylor_album_songs)
```

```{r}
library(tidytext)

tidy_taylor <- taylor_album_songs %>% 
  unnest(lyrics) %>% 
  unnest_tokens(word, lyric)
```

```{r}
tidy_taylor %>% 
  anti_join(get_stopwords()) %>% 
  count(track_name, word, sort = TRUE)
```
## Train a topic model
```{r}
lyrics_sparse <- tidy_taylor %>% 
  count(track_name, word) %>% 
  filter(n > 3) %>% 
  cast_sparse(track_name, word, n)

dim(lyrics_sparse)
```

```{r}
library(stm)

set.seed(123)
topic_model <- stm(lyrics_sparse, K = 13, verbose = FALSE)
summary(topic_model)
```
## Explore topic model results
```{r}
tidy(topic_model, matrix = "lift")

lyrics_gamma <- tidy(
  topic_model,
  matrix = "gamma",
  document_names = rownames(lyrics_sparse)
)
```

```{r}
lyrics_gamma %>% 
  left_join(
    taylor_album_songs %>% 
      select(album_name, document = track_name) %>% 
      mutate(album_name = fct_inorder(album_name))
  ) %>% View()
  mutate(topic = factor(topic)) %>% 
  ggplot(aes(gamma, topic, fill = topic)) +
  geom_boxplot(alpha = 0.7, show.legend = FALSE) +
  facet_wrap(vars(album_name)) +
  labs(x = expression(gamma))
```
## Estimate topic effects
```{r}
set.seed(123)

effects <- estimateEffect(
  1:13 ~ album_name,
  topic_model,
  taylor_album_songs %>% distinct(track_name, album_name) %>% arrange(track_name)
)

summary(effects)
```

```{r}
tidy(effects) %>% filter(term != "(Intercept)", p.value < 0.05)

tidy(topic_model, matrix = "lift") %>% filter(topic == 13)
```







